--------------------------------------------------------
--  파일이 생성됨 - 수요일-1월-15-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_00_CODE
--------------------------------------------------------

  CREATE TABLE "TB_00_CODE" 
   (	"CODE_GRP" VARCHAR2(20 BYTE), 
	"CODE" VARCHAR2(2 BYTE), 
	"CODE_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_00_CODE"."CODE_GRP" IS '코드그룹';
   COMMENT ON COLUMN "TB_00_CODE"."CODE" IS '코드';
   COMMENT ON COLUMN "TB_00_CODE"."CODE_NAME" IS '코드명';
   COMMENT ON TABLE "TB_00_CODE"  IS '공통코드';
--------------------------------------------------------
--  DDL for Table TB_00_COMMENT
--------------------------------------------------------

  CREATE TABLE "TB_00_COMMENT" 
   (	"GUBUN" VARCHAR2(2 BYTE), 
	"SEQ" VARCHAR2(8 BYTE), 
	"HR_SEQ" VARCHAR2(8 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE, 
	"WRITER" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_00_COMMENT"."GUBUN" IS '구분';
   COMMENT ON COLUMN "TB_00_COMMENT"."SEQ" IS '댓글SEQ';
   COMMENT ON COLUMN "TB_00_COMMENT"."HR_SEQ" IS '상위글번호';
   COMMENT ON COLUMN "TB_00_COMMENT"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_00_COMMENT"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_00_COMMENT"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_00_COMMENT"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_00_COMMENT"."UDT_DATE" IS '수정일';
   COMMENT ON COLUMN "TB_00_COMMENT"."WRITER" IS '작성자';
   COMMENT ON TABLE "TB_00_COMMENT"  IS '댓글';
--------------------------------------------------------
--  DDL for Table TB_00_MEMBER
--------------------------------------------------------

  CREATE TABLE "TB_00_MEMBER" 
   (	"MEMBER_SEQ" VARCHAR2(8 BYTE), 
	"MEMBER_NAME" VARCHAR2(20 BYTE), 
	"SCHOOL_NAME" VARCHAR2(50 BYTE), 
	"POSITION" VARCHAR2(2 BYTE), 
	"USER_ID" VARCHAR2(50 BYTE), 
	"SEN_EMAIL" VARCHAR2(100 BYTE), 
	"ADMIN_YN" VARCHAR2(1 BYTE) DEFAULT NULL, 
	"ADMIN_PW" VARCHAR2(8 BYTE), 
	"APPROVE_YN" VARCHAR2(1 BYTE) DEFAULT NULL, 
	"SCHOOL_TYPE" VARCHAR2(2 BYTE), 
	"REG_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_00_MEMBER"."MEMBER_SEQ" IS '회원번호';
   COMMENT ON COLUMN "TB_00_MEMBER"."MEMBER_NAME" IS '이름';
   COMMENT ON COLUMN "TB_00_MEMBER"."SCHOOL_NAME" IS '학교명';
   COMMENT ON COLUMN "TB_00_MEMBER"."POSITION" IS '직위';
   COMMENT ON COLUMN "TB_00_MEMBER"."USER_ID" IS 'USER_ID';
   COMMENT ON COLUMN "TB_00_MEMBER"."SEN_EMAIL" IS 'SEN 메일';
   COMMENT ON COLUMN "TB_00_MEMBER"."ADMIN_YN" IS '관리자여부';
   COMMENT ON COLUMN "TB_00_MEMBER"."ADMIN_PW" IS '관리자 비밀번호';
   COMMENT ON COLUMN "TB_00_MEMBER"."APPROVE_YN" IS '승인여부';
   COMMENT ON COLUMN "TB_00_MEMBER"."SCHOOL_TYPE" IS '학교급';
   COMMENT ON COLUMN "TB_00_MEMBER"."REG_DATE" IS '등록일자';
   COMMENT ON TABLE "TB_00_MEMBER"  IS '회원관리';
   
--------------------------------------------------------
-- User
  CREATE TABLE "TB_00_USER" 
   (	
    "USER_ID" VARCHAR2(50 BYTE), 
	"USER_NAME" VARCHAR2(20 BYTE), 
    "USER_PWD" VARCHAR2(50 BYTE),
	"ADMIN_YN" VARCHAR2(1 BYTE) DEFAULT 'N' 
	); 

   COMMENT ON COLUMN "TB_00_USER"."USER_ID" IS '아이디';
   COMMENT ON COLUMN "TB_00_USER"."USER_PWD" IS '비밀번호';
   COMMENT ON COLUMN "TB_00_USER"."USER_NAME" IS '회원이름';
   COMMENT ON COLUMN "TB_00_USER"."ADMIN_YN" IS '관리자여부';

   
   
--------------------------------------------------------
--  DDL for Table TB_00_POPUP
--------------------------------------------------------

  CREATE TABLE "TB_00_POPUP" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"STR_DATE" VARCHAR2(10 BYTE), 
	"END_DATE" VARCHAR2(10 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE, 
	"USE_YN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"BG_STYLE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_00_POPUP"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_00_POPUP"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_00_POPUP"."STR_DATE" IS '시작일자';
   COMMENT ON COLUMN "TB_00_POPUP"."END_DATE" IS '종료일자';
   COMMENT ON COLUMN "TB_00_POPUP"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_00_POPUP"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_00_POPUP"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_00_POPUP"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_00_POPUP"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_00_POPUP"."UDT_DATE" IS '수정일';
   COMMENT ON COLUMN "TB_00_POPUP"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "TB_00_POPUP"."BG_STYLE" IS '배경스타일';
   COMMENT ON TABLE "TB_00_POPUP"  IS '팝업관리';
--------------------------------------------------------
--  DDL for Table TB_00_VISIT
--------------------------------------------------------

  CREATE TABLE "TB_00_VISIT" 
   (	"V_DATE" DATE
   );

   COMMENT ON COLUMN "TB_00_VISIT"."V_DATE" IS '날짜';
   COMMENT ON TABLE "TB_00_VISIT"  IS '방문자 수';
--------------------------------------------------------
--  DDL for Table TB_01_BW
--------------------------------------------------------

  CREATE TABLE "TB_01_BW" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE, 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_01_BW"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_01_BW"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_01_BW"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_01_BW"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_01_BW"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_01_BW"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_01_BW"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_01_BW"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_01_BW"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_01_BW"."UDT_DATE" IS '수정일';
   COMMENT ON COLUMN "TB_01_BW"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_01_BW"."WRITER" IS '작성자';
   COMMENT ON TABLE "TB_01_BW"  IS '학교급식 기본방향';
--------------------------------------------------------
--  DDL for Table TB_02_AP
--------------------------------------------------------

  CREATE TABLE "TB_02_AP" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE, 
	"WRITER" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_02_AP"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_02_AP"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_02_AP"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_02_AP"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_02_AP"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_02_AP"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_02_AP"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_02_AP"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_02_AP"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_02_AP"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_02_AP"."UDT_DATE" IS '수정일';
   COMMENT ON COLUMN "TB_02_AP"."WRITER" IS '작성자';
   COMMENT ON TABLE "TB_02_AP"  IS '안전사고 예방';
--------------------------------------------------------
--  DDL for Table TB_02_HS
--------------------------------------------------------

  CREATE TABLE "TB_02_HS" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE, 
	"WRITER" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_02_HS"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_02_HS"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_02_HS"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_02_HS"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_02_HS"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_02_HS"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_02_HS"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_02_HS"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_02_HS"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_02_HS"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_02_HS"."UDT_DATE" IS '수정일';
   COMMENT ON COLUMN "TB_02_HS"."WRITER" IS '작성자';
   COMMENT ON TABLE "TB_02_HS"  IS '학교급식 위생관리';
--------------------------------------------------------
--  DDL for Table TB_02_IR
--------------------------------------------------------

  CREATE TABLE "TB_02_IR" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_02_IR"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_02_IR"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_02_IR"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_02_IR"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_02_IR"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_02_IR"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_02_IR"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_02_IR"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_02_IR"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_02_IR"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_02_IR"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_02_IR"."UDT_DATE" IS '수정일';
   COMMENT ON TABLE "TB_02_IR"  IS '위생·안전성 검사 결과';
--------------------------------------------------------
--  DDL for Table TB_03_AC
--------------------------------------------------------

  CREATE TABLE "TB_03_AC" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"BUY_YEAR" VARCHAR2(4 BYTE) DEFAULT TO_CHAR(SYSDATE, 'yyyy'), 
	"SCHOOL_NAME" VARCHAR2(200 BYTE), 
	"SCHOOL_TYPE" VARCHAR2(2 BYTE), 
	"SELL_YN" VARCHAR2(2 BYTE) DEFAULT 'N', 
	"STANDARD" VARCHAR2(100 BYTE), 
	"CAPACITY" VARCHAR2(100 BYTE), 
	"CLASSIFY" VARCHAR2(2 BYTE), 
	"HEAT_WAY" VARCHAR2(2 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"IMG1" VARCHAR2(200 BYTE), 
	"IMG2" VARCHAR2(200 BYTE), 
	"IMG3" VARCHAR2(200 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_03_AC"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_03_AC"."NAME" IS '기구명';
   COMMENT ON COLUMN "TB_03_AC"."BUY_YEAR" IS '구입년도';
   COMMENT ON COLUMN "TB_03_AC"."SCHOOL_NAME" IS '학교명';
   COMMENT ON COLUMN "TB_03_AC"."SCHOOL_TYPE" IS '학교구분';
   COMMENT ON COLUMN "TB_03_AC"."SELL_YN" IS '완료여부';
   COMMENT ON COLUMN "TB_03_AC"."STANDARD" IS '규격';
   COMMENT ON COLUMN "TB_03_AC"."CAPACITY" IS '용량';
   COMMENT ON COLUMN "TB_03_AC"."CLASSIFY" IS '기구분류';
   COMMENT ON COLUMN "TB_03_AC"."HEAT_WAY" IS '열원방식';
   COMMENT ON COLUMN "TB_03_AC"."DESCRIPTION" IS '내용 및 기구상태';
   COMMENT ON COLUMN "TB_03_AC"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_03_AC"."IMG1" IS '이미지1';
   COMMENT ON COLUMN "TB_03_AC"."IMG2" IS '이미지2';
   COMMENT ON COLUMN "TB_03_AC"."IMG3" IS '이미지3';
   COMMENT ON COLUMN "TB_03_AC"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_03_AC"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_03_AC"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_03_AC"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_03_AC"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_03_AC"."UDT_DATE" IS '수정일';
   COMMENT ON TABLE "TB_03_AC"  IS '급식기구 관리전환';
--------------------------------------------------------
--  DDL for Table TB_03_IB
--------------------------------------------------------

  CREATE TABLE "TB_03_IB" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_03_IB"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_03_IB"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_03_IB"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_03_IB"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_03_IB"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_03_IB"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_03_IB"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_03_IB"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_03_IB"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_03_IB"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_03_IB"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_03_IB"."UDT_DATE" IS '수정일';
   COMMENT ON TABLE "TB_03_IB"  IS '급식환경 개선사업';
--------------------------------------------------------
--  DDL for Table TB_03_IC
--------------------------------------------------------

  CREATE TABLE "TB_03_IC" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"IMG1" VARCHAR2(200 BYTE), 
	"IMG2" VARCHAR2(200 BYTE), 
	"IMG3" VARCHAR2(200 BYTE), 
	"IMG4" VARCHAR2(200 BYTE), 
	"IMG5" VARCHAR2(200 BYTE), 
	"IMG6" VARCHAR2(200 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_03_IC"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_03_IC"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_03_IC"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_03_IC"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_03_IC"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_03_IC"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_03_IC"."IMG1" IS '이미지1';
   COMMENT ON COLUMN "TB_03_IC"."IMG2" IS '이미지2';
   COMMENT ON COLUMN "TB_03_IC"."IMG3" IS '이미지3';
   COMMENT ON COLUMN "TB_03_IC"."IMG4" IS '이미지4';
   COMMENT ON COLUMN "TB_03_IC"."IMG5" IS '이미지5';
   COMMENT ON COLUMN "TB_03_IC"."IMG6" IS '이미지6';
   COMMENT ON COLUMN "TB_03_IC"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_03_IC"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_03_IC"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_03_IC"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_03_IC"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_03_IC"."UDT_DATE" IS '수정일';
   COMMENT ON TABLE "TB_03_IC"  IS '급식시설 개선사례';
--------------------------------------------------------
--  DDL for Table TB_04_FP
--------------------------------------------------------

  CREATE TABLE "TB_04_FP" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_04_FP"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_04_FP"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_04_FP"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_04_FP"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_04_FP"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_04_FP"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_04_FP"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_04_FP"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_04_FP"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_04_FP"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_04_FP"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_04_FP"."UDT_DATE" IS '수정일';
   COMMENT ON TABLE "TB_04_FP"  IS '식재료 구매·관리';
--------------------------------------------------------
--  DDL for Table TB_04_IE
--------------------------------------------------------

  CREATE TABLE "TB_04_IE" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_04_IE"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_04_IE"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_04_IE"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_04_IE"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_04_IE"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_04_IE"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_04_IE"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_04_IE"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_04_IE"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_04_IE"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_04_IE"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_04_IE"."UDT_DATE" IS '수정일';
   COMMENT ON TABLE "TB_04_IE"  IS '부적합 납품업체';
--------------------------------------------------------
--  DDL for Table TB_05_APPLICATION
--------------------------------------------------------

  CREATE TABLE "TB_05_APPLICATION" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"LOC_SEQ" VARCHAR2(2 BYTE), 
	"SEX" VARCHAR2(2 BYTE), 
	"JOB" VARCHAR2(2 BYTE), 
	"GUBUN" VARCHAR2(2 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"ATTACH_NAME" VARCHAR2(50 BYTE), 
	"ATTACH_PATH" VARCHAR2(100 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE, 
	"AGE" VARCHAR2(3 BYTE), 
	"END_YN" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_05_APPLICATION"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_05_APPLICATION"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_05_APPLICATION"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_05_APPLICATION"."LOC_SEQ" IS '지역';
   COMMENT ON COLUMN "TB_05_APPLICATION"."SEX" IS '성별';
   COMMENT ON COLUMN "TB_05_APPLICATION"."JOB" IS '직종';
   COMMENT ON COLUMN "TB_05_APPLICATION"."GUBUN" IS '근무형태';
   COMMENT ON COLUMN "TB_05_APPLICATION"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "TB_05_APPLICATION"."PHONE" IS '연락처';
   COMMENT ON COLUMN "TB_05_APPLICATION"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_05_APPLICATION"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_05_APPLICATION"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_05_APPLICATION"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_05_APPLICATION"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_05_APPLICATION"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_05_APPLICATION"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_05_APPLICATION"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_05_APPLICATION"."UDT_DATE" IS '수정일';
   COMMENT ON COLUMN "TB_05_APPLICATION"."AGE" IS '연령';
   COMMENT ON COLUMN "TB_05_APPLICATION"."END_YN" IS '마감여부';
   COMMENT ON TABLE "TB_05_APPLICATION"  IS '급식인력풀(구직)';
--------------------------------------------------------
--  DDL for Table TB_05_NF
--------------------------------------------------------

  CREATE TABLE "TB_05_NF" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_05_NF"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_05_NF"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_05_NF"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_05_NF"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_05_NF"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_05_NF"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_05_NF"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_05_NF"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_05_NF"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_05_NF"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_05_NF"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_05_NF"."UDT_DATE" IS '수정일';
   COMMENT ON TABLE "TB_05_NF"  IS '영양·식생활교육';
--------------------------------------------------------
--  DDL for Table TB_05_PA
--------------------------------------------------------

  CREATE TABLE "TB_05_PA" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"IMG1" VARCHAR2(200 BYTE), 
	"IMG2" VARCHAR2(200 BYTE), 
	"IMG3" VARCHAR2(200 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_05_PA"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_05_PA"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_05_PA"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_05_PA"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_05_PA"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_05_PA"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_05_PA"."IMG1" IS '이미지1';
   COMMENT ON COLUMN "TB_05_PA"."IMG2" IS '이미지2';
   COMMENT ON COLUMN "TB_05_PA"."IMG3" IS '이미지3';
   COMMENT ON COLUMN "TB_05_PA"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_05_PA"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_05_PA"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_05_PA"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_05_PA"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_05_PA"."UDT_DATE" IS '수정일';
   COMMENT ON TABLE "TB_05_PA"  IS '학교급식 특색활동';
--------------------------------------------------------
--  DDL for Table TB_05_RECRUIT
--------------------------------------------------------

  CREATE TABLE "TB_05_RECRUIT" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"SCHOOL_NAME" VARCHAR2(200 BYTE), 
	"SCHOOL_TYPE" VARCHAR2(2 BYTE), 
	"LOC_SEQ" VARCHAR2(2 BYTE), 
	"JOB" VARCHAR2(2 BYTE), 
	"GUBUN" VARCHAR2(2 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"ATTACH_NAME" VARCHAR2(50 BYTE), 
	"ATTACH_PATH" VARCHAR2(100 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE, 
	"END_YN" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_05_RECRUIT"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_05_RECRUIT"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_05_RECRUIT"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_05_RECRUIT"."SCHOOL_NAME" IS '학교명';
   COMMENT ON COLUMN "TB_05_RECRUIT"."SCHOOL_TYPE" IS '학교구분';
   COMMENT ON COLUMN "TB_05_RECRUIT"."LOC_SEQ" IS '지역';
   COMMENT ON COLUMN "TB_05_RECRUIT"."JOB" IS '직종';
   COMMENT ON COLUMN "TB_05_RECRUIT"."GUBUN" IS '근무형태';
   COMMENT ON COLUMN "TB_05_RECRUIT"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "TB_05_RECRUIT"."PHONE" IS '연락처';
   COMMENT ON COLUMN "TB_05_RECRUIT"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_05_RECRUIT"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_05_RECRUIT"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_05_RECRUIT"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_05_RECRUIT"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_05_RECRUIT"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_05_RECRUIT"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_05_RECRUIT"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_05_RECRUIT"."UDT_DATE" IS '수정일';
   COMMENT ON COLUMN "TB_05_RECRUIT"."END_YN" IS '마감여부';
   COMMENT ON TABLE "TB_05_RECRUIT"  IS '급식인력풀(구인)';
--------------------------------------------------------
--  DDL for Table TB_05_RM
--------------------------------------------------------

  CREATE TABLE "TB_05_RM" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"IMG1" VARCHAR2(200 BYTE), 
	"IMG2" VARCHAR2(200 BYTE), 
	"IMG3" VARCHAR2(200 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_05_RM"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_05_RM"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_05_RM"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_05_RM"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_05_RM"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_05_RM"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_05_RM"."IMG1" IS '이미지1';
   COMMENT ON COLUMN "TB_05_RM"."IMG2" IS '이미지2';
   COMMENT ON COLUMN "TB_05_RM"."IMG3" IS '이미지3';
   COMMENT ON COLUMN "TB_05_RM"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_05_RM"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_05_RM"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_05_RM"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_05_RM"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_05_RM"."UDT_DATE" IS '수정일';
   COMMENT ON TABLE "TB_05_RM"  IS '추천식단';
--------------------------------------------------------
--  DDL for Table TB_05_RR
--------------------------------------------------------

  CREATE TABLE "TB_05_RR" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"IMG1" VARCHAR2(200 BYTE), 
	"IMG2" VARCHAR2(200 BYTE), 
	"IMG3" VARCHAR2(200 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_05_RR"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_05_RR"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_05_RR"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_05_RR"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_05_RR"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_05_RR"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_05_RR"."IMG1" IS '이미지1';
   COMMENT ON COLUMN "TB_05_RR"."IMG2" IS '이미지2';
   COMMENT ON COLUMN "TB_05_RR"."IMG3" IS '이미지3';
   COMMENT ON COLUMN "TB_05_RR"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_05_RR"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_05_RR"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_05_RR"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_05_RR"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_05_RR"."UDT_DATE" IS '수정일';
   COMMENT ON TABLE "TB_05_RR"  IS '추천레시피';
--------------------------------------------------------
--  DDL for Table TB_06_CS
--------------------------------------------------------

  CREATE TABLE "TB_06_CS" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE, 
	"WRITER" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_06_CS"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_06_CS"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_06_CS"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_06_CS"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_06_CS"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_06_CS"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_06_CS"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_06_CS"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_06_CS"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_06_CS"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_06_CS"."UDT_DATE" IS '수정일';
   COMMENT ON COLUMN "TB_06_CS"."WRITER" IS '작성자';
   COMMENT ON TABLE "TB_06_CS"  IS '조리사(원) 이야기';
--------------------------------------------------------
--  DDL for Table TB_06_FB
--------------------------------------------------------

  CREATE TABLE "TB_06_FB" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_06_FB"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_06_FB"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_06_FB"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_06_FB"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_06_FB"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_06_FB"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_06_FB"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_06_FB"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_06_FB"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_06_FB"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_06_FB"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_06_FB"."UDT_DATE" IS '수정일';
   COMMENT ON TABLE "TB_06_FB"  IS '자유게시판';
--------------------------------------------------------
--  DDL for Table TB_06_NS
--------------------------------------------------------

  CREATE TABLE "TB_06_NS" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE, 
	"WRITER" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_06_NS"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_06_NS"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_06_NS"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_06_NS"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_06_NS"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_06_NS"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_06_NS"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_06_NS"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_06_NS"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_06_NS"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_06_NS"."UDT_DATE" IS '수정일';
   COMMENT ON COLUMN "TB_06_NS"."WRITER" IS '작성자';
   COMMENT ON TABLE "TB_06_NS"  IS '영양(교)사 이야기';
--------------------------------------------------------
--  DDL for Table TB_06_RS
--------------------------------------------------------

  CREATE TABLE "TB_06_RS" 
   (	"SUR_SEQ" VARCHAR2(8 BYTE), 
	"SUR_TITLE" VARCHAR2(200 BYTE), 
	"QUE_CNT" VARCHAR2(2 BYTE), 
	"SUR_SAT_DATE" VARCHAR2(10 BYTE), 
	"SUR_END_DATE" VARCHAR2(10 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_06_RS"."SUR_SEQ" IS '설문번호';
   COMMENT ON COLUMN "TB_06_RS"."SUR_TITLE" IS '제목';
   COMMENT ON COLUMN "TB_06_RS"."QUE_CNT" IS '문제수';
   COMMENT ON COLUMN "TB_06_RS"."SUR_SAT_DATE" IS '설문시작일자';
   COMMENT ON COLUMN "TB_06_RS"."SUR_END_DATE" IS '설문종료일자';
   COMMENT ON COLUMN "TB_06_RS"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_06_RS"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_06_RS"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_06_RS"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_06_RS"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_06_RS"."UDT_DATE" IS '수정일';
   COMMENT ON TABLE "TB_06_RS"  IS '설문조사 정보';
--------------------------------------------------------
--  DDL for Table TB_06_RSI
--------------------------------------------------------

  CREATE TABLE "TB_06_RSI" 
   (	"SURI_SEQ" VARCHAR2(8 BYTE), 
	"SUR_SEQ" VARCHAR2(8 BYTE), 
	"SURQ_SEQ" VARCHAR2(8 BYTE), 
	"SURI_TITLE1" VARCHAR2(200 BYTE), 
	"SURI_TITLE2" VARCHAR2(200 BYTE), 
	"SURI_TITLE3" VARCHAR2(200 BYTE), 
	"SURI_TITLE4" VARCHAR2(200 BYTE), 
	"SURI_TITLE5" VARCHAR2(200 BYTE), 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE, 
	"SURI_NUM1" VARCHAR2(1 BYTE) DEFAULT 1, 
	"SURI_NUM2" VARCHAR2(1 BYTE) DEFAULT 2, 
	"SURI_NUM3" VARCHAR2(1 BYTE) DEFAULT 3, 
	"SURI_NUM4" VARCHAR2(1 BYTE) DEFAULT 4, 
	"SURI_NUM5" VARCHAR2(1 BYTE) DEFAULT 5
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_06_RSI"."SURI_SEQ" IS '문항번호';
   COMMENT ON COLUMN "TB_06_RSI"."SUR_SEQ" IS '설문번호';
   COMMENT ON COLUMN "TB_06_RSI"."SURQ_SEQ" IS '문제번호';
   COMMENT ON COLUMN "TB_06_RSI"."SURI_TITLE1" IS '문항제목1';
   COMMENT ON COLUMN "TB_06_RSI"."SURI_TITLE2" IS '문항제목2';
   COMMENT ON COLUMN "TB_06_RSI"."SURI_TITLE3" IS '문항제목3';
   COMMENT ON COLUMN "TB_06_RSI"."SURI_TITLE4" IS '문항제목4';
   COMMENT ON COLUMN "TB_06_RSI"."SURI_TITLE5" IS '문항제목5';
   COMMENT ON COLUMN "TB_06_RSI"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_06_RSI"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_06_RSI"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_06_RSI"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_06_RSI"."UDT_DATE" IS '수정일';
   COMMENT ON COLUMN "TB_06_RSI"."SURI_NUM1" IS '문항1';
   COMMENT ON COLUMN "TB_06_RSI"."SURI_NUM2" IS '문항2';
   COMMENT ON COLUMN "TB_06_RSI"."SURI_NUM3" IS '문항3';
   COMMENT ON COLUMN "TB_06_RSI"."SURI_NUM4" IS '문항4';
   COMMENT ON COLUMN "TB_06_RSI"."SURI_NUM5" IS '문항5';
   COMMENT ON TABLE "TB_06_RSI"  IS '설문조사 문항';
--------------------------------------------------------
--  DDL for Table TB_06_RSQ
--------------------------------------------------------

  CREATE TABLE "TB_06_RSQ" 
   (	"SURQ_SEQ" VARCHAR2(8 BYTE), 
	"SUR_SEQ" VARCHAR2(8 BYTE), 
	"SURQ_TITLE" VARCHAR2(200 BYTE), 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_06_RSQ"."SURQ_SEQ" IS '문제번호';
   COMMENT ON COLUMN "TB_06_RSQ"."SUR_SEQ" IS '설문번호';
   COMMENT ON COLUMN "TB_06_RSQ"."SURQ_TITLE" IS '문제';
   COMMENT ON COLUMN "TB_06_RSQ"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_06_RSQ"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_06_RSQ"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_06_RSQ"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_06_RSQ"."UDT_DATE" IS '수정일';
   COMMENT ON TABLE "TB_06_RSQ"  IS '설문조사 문제';
--------------------------------------------------------
--  DDL for Table TB_06_RSR
--------------------------------------------------------

  CREATE TABLE "TB_06_RSR" 
   (	"SURR_SEQ" VARCHAR2(8 BYTE), 
	"SUR_SEQ" VARCHAR2(8 BYTE), 
	"SURQ_SEQ" VARCHAR2(8 BYTE), 
	"SURI_SEQ" VARCHAR2(8 BYTE), 
	"SURI_NUM" VARCHAR2(250 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE, 
	"SURQ_TITLE" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_06_RSR"."SURR_SEQ" IS '설문결과번호';
   COMMENT ON COLUMN "TB_06_RSR"."SUR_SEQ" IS '설문번호';
   COMMENT ON COLUMN "TB_06_RSR"."SURQ_SEQ" IS '문제번호';
   COMMENT ON COLUMN "TB_06_RSR"."SURI_SEQ" IS '문항번호';
   COMMENT ON COLUMN "TB_06_RSR"."SURI_NUM" IS '선택문항';
   COMMENT ON COLUMN "TB_06_RSR"."DESCRIPTION" IS '선택사유';
   COMMENT ON COLUMN "TB_06_RSR"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_06_RSR"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_06_RSR"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_06_RSR"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_06_RSR"."UDT_DATE" IS '수정일';
   COMMENT ON COLUMN "TB_06_RSR"."SURQ_TITLE" IS '문제';
   COMMENT ON TABLE "TB_06_RSR"  IS '설문조사 결과';
--------------------------------------------------------
--  DDL for Table TB_07_BR
--------------------------------------------------------

  CREATE TABLE "TB_07_BR" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"GUBUN" VARCHAR2(2 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_07_BR"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_07_BR"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_07_BR"."GUBUN" IS '업무/서식';
   COMMENT ON COLUMN "TB_07_BR"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_07_BR"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_07_BR"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_07_BR"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_07_BR"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_07_BR"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_07_BR"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_07_BR"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_07_BR"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_07_BR"."UDT_DATE" IS '수정일';
   COMMENT ON TABLE "TB_07_BR"  IS '업무자료실';
--------------------------------------------------------
--  DDL for Table TB_07_FAQ
--------------------------------------------------------

  CREATE TABLE "TB_07_FAQ" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_07_FAQ"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_07_FAQ"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_07_FAQ"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_07_FAQ"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_07_FAQ"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_07_FAQ"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_07_FAQ"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_07_FAQ"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_07_FAQ"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_07_FAQ"."UDT_DATE" IS '수정일';
   COMMENT ON TABLE "TB_07_FAQ"  IS 'FAQ';
--------------------------------------------------------
--  DDL for Table TB_07_FN
--------------------------------------------------------

  CREATE TABLE "TB_07_FN" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_07_FN"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_07_FN"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_07_FN"."ATTACH_NAME" IS '첨부파일 이름';
   COMMENT ON COLUMN "TB_07_FN"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_07_FN"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_07_FN"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_07_FN"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_07_FN"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_07_FN"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_07_FN"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_07_FN"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_07_FN"."UDT_DATE" IS '수정일';
   COMMENT ON TABLE "TB_07_FN"  IS '급식소식';
--------------------------------------------------------
--  DDL for Table TB_07_TE
--------------------------------------------------------

  CREATE TABLE "TB_07_TE" 
   (	"SEQ" VARCHAR2(8 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"GUBUN" VARCHAR2(2 BYTE), 
	"STR_DATE" VARCHAR2(10 BYTE), 
	"END_DATE" VARCHAR2(10 BYTE), 
	"ATTACH_NAME" VARCHAR2(200 BYTE), 
	"ATTACH_PATH" VARCHAR2(200 BYTE), 
	"PW" VARCHAR2(8 BYTE), 
	"IMG1" VARCHAR2(200 BYTE), 
	"IMG2" VARCHAR2(200 BYTE), 
	"IMG3" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"UP_SEQ" VARCHAR2(8 BYTE), 
	"HITS" VARCHAR2(8 BYTE) DEFAULT 0, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_NAME" VARCHAR2(8 BYTE), 
	"REG_DATE" DATE, 
	"UDT_NAME" VARCHAR2(8 BYTE), 
	"UDT_DATE" DATE, 
	"TURN" VARCHAR2(8 BYTE) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;

   COMMENT ON COLUMN "TB_07_TE"."SEQ" IS 'SEQ';
   COMMENT ON COLUMN "TB_07_TE"."TITLE" IS '제목';
   COMMENT ON COLUMN "TB_07_TE"."GUBUN" IS '분류';
   COMMENT ON COLUMN "TB_07_TE"."STR_DATE" IS '시작일자';
   COMMENT ON COLUMN "TB_07_TE"."END_DATE" IS '종료일자';
   COMMENT ON COLUMN "TB_07_TE"."ATTACH_NAME" IS '첨부파일 명';
   COMMENT ON COLUMN "TB_07_TE"."ATTACH_PATH" IS '첨부파일 경로';
   COMMENT ON COLUMN "TB_07_TE"."PW" IS '비밀번호';
   COMMENT ON COLUMN "TB_07_TE"."IMG1" IS '이미지1';
   COMMENT ON COLUMN "TB_07_TE"."IMG2" IS '이미지2';
   COMMENT ON COLUMN "TB_07_TE"."IMG3" IS '이미지3';
   COMMENT ON COLUMN "TB_07_TE"."DESCRIPTION" IS '내용';
   COMMENT ON COLUMN "TB_07_TE"."UP_SEQ" IS '상위문서번호';
   COMMENT ON COLUMN "TB_07_TE"."HITS" IS '조회수';
   COMMENT ON COLUMN "TB_07_TE"."WRITER" IS '작성자';
   COMMENT ON COLUMN "TB_07_TE"."REG_NAME" IS '등록자';
   COMMENT ON COLUMN "TB_07_TE"."REG_DATE" IS '등록일';
   COMMENT ON COLUMN "TB_07_TE"."UDT_NAME" IS '수정자';
   COMMENT ON COLUMN "TB_07_TE"."UDT_DATE" IS '수정일';
   COMMENT ON COLUMN "TB_07_TE"."TURN" IS '순번';
   COMMENT ON TABLE "TB_07_TE"  IS '연수·행사';
--------------------------------------------------------
--  DDL for Index PK_TB_06_NS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_06_NS" ON "TB_06_NS" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_06_RSQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_06_RSQ" ON "TB_06_RSQ" ("SURQ_SEQ", "SUR_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index TB_00_MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TB_00_MEMBER_PK" ON "TB_00_MEMBER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FOOD" ;
--------------------------------------------------------
--  DDL for Index PK_TB_05_APPLICATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_05_APPLICATION" ON "TB_05_APPLICATION" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_01_BW
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_01_BW" ON "TB_01_BW" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_05_NF
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_05_NF" ON "TB_05_NF" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_00_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_00_CODE" ON "TB_00_CODE" ("CODE_GRP", "CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_05_PA
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_05_PA" ON "TB_05_PA" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_02_IR
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_02_IR" ON "TB_02_IR" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_06_RSI
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_06_RSI" ON "TB_06_RSI" ("SURI_SEQ", "SUR_SEQ", "SURQ_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_05_RM
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_05_RM" ON "TB_05_RM" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_05_RECRUIT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_05_RECRUIT" ON "TB_05_RECRUIT" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_06_RSR
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_06_RSR" ON "TB_06_RSR" ("SURR_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_07_FAQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_07_FAQ" ON "TB_07_FAQ" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_07_TE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_07_TE" ON "TB_07_TE" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_02_AP
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_02_AP" ON "TB_02_AP" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_00_COMMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_00_COMMENT" ON "TB_00_COMMENT" ("GUBUN", "SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_03_IB
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_03_IB" ON "TB_03_IB" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_02_HS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_02_HS" ON "TB_02_HS" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_07_FN
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_07_FN" ON "TB_07_FN" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_03_IC
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_03_IC" ON "TB_03_IC" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_04_IE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_04_IE" ON "TB_04_IE" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_06_FB
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_06_FB" ON "TB_06_FB" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_06_RS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_06_RS" ON "TB_06_RS" ("SUR_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_03_AC
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_03_AC" ON "TB_03_AC" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_05_RR
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_05_RR" ON "TB_05_RR" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_06_CS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_06_CS" ON "TB_06_CS" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_00_POPUP
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_00_POPUP" ON "TB_00_POPUP" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_04_FP
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_04_FP" ON "TB_04_FP" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  DDL for Index PK_TB_07_BR
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TB_07_BR" ON "TB_07_BR" ("SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY" ;
--------------------------------------------------------
--  Constraints for Table TB_00_POPUP
--------------------------------------------------------

  ALTER TABLE "TB_00_POPUP" MODIFY ("BG_STYLE" NOT NULL ENABLE);
  ALTER TABLE "TB_00_POPUP" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "TB_00_POPUP" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_00_POPUP" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_00_POPUP" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_00_POPUP" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_00_POPUP" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_00_POPUP" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_00_POPUP" MODIFY ("STR_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_00_POPUP" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_00_POPUP" MODIFY ("SEQ" NOT NULL ENABLE);
  ALTER TABLE "TB_00_POPUP" ADD CONSTRAINT "PK_TB_00_POPUP" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_05_RM
--------------------------------------------------------

  ALTER TABLE "TB_05_RM" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RM" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RM" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RM" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RM" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RM" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RM" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RM" ADD CONSTRAINT "PK_TB_05_RM" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_06_RSQ
--------------------------------------------------------

  ALTER TABLE "TB_06_RSQ" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSQ" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSQ" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSQ" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSQ" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSQ" MODIFY ("SUR_SEQ" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSQ" MODIFY ("SURQ_SEQ" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSQ" ADD CONSTRAINT "PK_TB_06_RSQ" PRIMARY KEY ("SURQ_SEQ", "SUR_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_05_PA
--------------------------------------------------------

  ALTER TABLE "TB_05_PA" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_PA" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_05_PA" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_PA" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_05_PA" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_05_PA" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_05_PA" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_PA" ADD CONSTRAINT "PK_TB_05_PA" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_07_TE
--------------------------------------------------------

  ALTER TABLE "TB_07_TE" MODIFY ("TURN" NOT NULL ENABLE);
  ALTER TABLE "TB_07_TE" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_07_TE" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_07_TE" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_07_TE" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_07_TE" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_07_TE" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_07_TE" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_07_TE" MODIFY ("STR_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_07_TE" MODIFY ("GUBUN" NOT NULL ENABLE);
  ALTER TABLE "TB_07_TE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_07_TE" MODIFY ("SEQ" NOT NULL ENABLE);
  ALTER TABLE "TB_07_TE" ADD CONSTRAINT "PK_TB_07_TE" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_04_IE
--------------------------------------------------------

  ALTER TABLE "TB_04_IE" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_04_IE" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_04_IE" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_04_IE" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_04_IE" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_04_IE" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_04_IE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_04_IE" ADD CONSTRAINT "PK_TB_04_IE" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_00_CODE
--------------------------------------------------------

  ALTER TABLE "TB_00_CODE" MODIFY ("CODE_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_00_CODE" ADD CONSTRAINT "PK_TB_00_CODE" PRIMARY KEY ("CODE_GRP", "CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_07_FN
--------------------------------------------------------

  ALTER TABLE "TB_07_FN" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_07_FN" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_07_FN" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_07_FN" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_07_FN" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_07_FN" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_07_FN" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_07_FN" ADD CONSTRAINT "PK_TB_07_FN" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_05_RR
--------------------------------------------------------

  ALTER TABLE "TB_05_RR" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RR" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RR" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RR" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RR" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RR" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RR" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RR" ADD CONSTRAINT "PK_TB_05_RR" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_05_RECRUIT
--------------------------------------------------------

  ALTER TABLE "TB_05_RECRUIT" MODIFY ("END_YN" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RECRUIT" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RECRUIT" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RECRUIT" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RECRUIT" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RECRUIT" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RECRUIT" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RECRUIT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RECRUIT" MODIFY ("GUBUN" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RECRUIT" MODIFY ("JOB" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RECRUIT" MODIFY ("LOC_SEQ" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RECRUIT" MODIFY ("SCHOOL_TYPE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RECRUIT" MODIFY ("SCHOOL_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RECRUIT" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RECRUIT" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RECRUIT" MODIFY ("SEQ" NOT NULL ENABLE);
  ALTER TABLE "TB_05_RECRUIT" ADD CONSTRAINT "PK_TB_05_RECRUIT" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_03_IB
--------------------------------------------------------

  ALTER TABLE "TB_03_IB" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_03_IB" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_03_IB" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_03_IB" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_03_IB" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_03_IB" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_03_IB" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_03_IB" ADD CONSTRAINT "PK_TB_03_IB" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_06_NS
--------------------------------------------------------

  ALTER TABLE "TB_06_NS" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_06_NS" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_NS" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_06_NS" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_NS" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_06_NS" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_06_NS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_NS" ADD CONSTRAINT "PK_TB_06_NS" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_02_IR
--------------------------------------------------------

  ALTER TABLE "TB_02_IR" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_02_IR" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_02_IR" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_02_IR" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_02_IR" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_02_IR" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_02_IR" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_02_IR" ADD CONSTRAINT "PK_TB_02_IR" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_01_BW
--------------------------------------------------------

  ALTER TABLE "TB_01_BW" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_01_BW" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_01_BW" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_01_BW" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_01_BW" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_01_BW" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_01_BW" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_01_BW" ADD CONSTRAINT "PK_TB_01_BW" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_06_RSI
--------------------------------------------------------

  ALTER TABLE "TB_06_RSI" MODIFY ("SURI_NUM5" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSI" MODIFY ("SURI_NUM4" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSI" MODIFY ("SURI_NUM3" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSI" MODIFY ("SURI_NUM2" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSI" MODIFY ("SURI_NUM1" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSI" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSI" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSI" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSI" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSI" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSI" MODIFY ("SURQ_SEQ" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSI" MODIFY ("SUR_SEQ" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSI" MODIFY ("SURI_SEQ" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSI" ADD CONSTRAINT "PK_TB_06_RSI" PRIMARY KEY ("SURI_SEQ", "SUR_SEQ", "SURQ_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_05_NF
--------------------------------------------------------

  ALTER TABLE "TB_05_NF" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_NF" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_05_NF" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_NF" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_05_NF" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_05_NF" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_05_NF" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_NF" ADD CONSTRAINT "PK_TB_05_NF" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_02_HS
--------------------------------------------------------

  ALTER TABLE "TB_02_HS" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_02_HS" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_02_HS" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_02_HS" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_02_HS" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_02_HS" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_02_HS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_02_HS" ADD CONSTRAINT "PK_TB_02_HS" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_06_RS
--------------------------------------------------------

  ALTER TABLE "TB_06_RS" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RS" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RS" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RS" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RS" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RS" MODIFY ("SUR_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RS" MODIFY ("SUR_SAT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RS" MODIFY ("QUE_CNT" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RS" MODIFY ("SUR_TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RS" MODIFY ("SUR_SEQ" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RS" ADD CONSTRAINT "PK_TB_06_RS" PRIMARY KEY ("SUR_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_03_IC
--------------------------------------------------------

  ALTER TABLE "TB_03_IC" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_03_IC" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_03_IC" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_03_IC" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_03_IC" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_03_IC" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_03_IC" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_03_IC" ADD CONSTRAINT "PK_TB_03_IC" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_07_BR
--------------------------------------------------------

  ALTER TABLE "TB_07_BR" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_07_BR" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_07_BR" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_07_BR" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_07_BR" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_07_BR" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_07_BR" MODIFY ("GUBUN" NOT NULL ENABLE);
  ALTER TABLE "TB_07_BR" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_07_BR" ADD CONSTRAINT "PK_TB_07_BR" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_00_MEMBER
--------------------------------------------------------

  ALTER TABLE "TB_00_MEMBER" ADD CONSTRAINT "TB_00_MEMBER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FOOD"  ENABLE;
  ALTER TABLE "TB_00_MEMBER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_00_MEMBER" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_00_MEMBER" MODIFY ("APPROVE_YN" NOT NULL ENABLE);
  ALTER TABLE "TB_00_MEMBER" MODIFY ("ADMIN_YN" NOT NULL ENABLE);
  ALTER TABLE "TB_00_MEMBER" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_04_FP
--------------------------------------------------------

  ALTER TABLE "TB_04_FP" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_04_FP" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_04_FP" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_04_FP" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_04_FP" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_04_FP" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_04_FP" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_04_FP" ADD CONSTRAINT "PK_TB_04_FP" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_06_RSR
--------------------------------------------------------

  ALTER TABLE "TB_06_RSR" MODIFY ("SURQ_TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSR" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSR" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSR" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSR" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSR" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSR" MODIFY ("SURI_SEQ" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSR" MODIFY ("SURQ_SEQ" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSR" MODIFY ("SUR_SEQ" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSR" MODIFY ("SURR_SEQ" NOT NULL ENABLE);
  ALTER TABLE "TB_06_RSR" ADD CONSTRAINT "PK_TB_06_RSR" PRIMARY KEY ("SURR_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_00_COMMENT
--------------------------------------------------------

  ALTER TABLE "TB_00_COMMENT" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_00_COMMENT" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_00_COMMENT" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_00_COMMENT" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_00_COMMENT" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_00_COMMENT" ADD CONSTRAINT "PK_TB_00_COMMENT" PRIMARY KEY ("GUBUN", "SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_03_AC
--------------------------------------------------------

  ALTER TABLE "TB_03_AC" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_03_AC" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_03_AC" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_03_AC" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_03_AC" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_03_AC" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_03_AC" MODIFY ("CLASSIFY" NOT NULL ENABLE);
  ALTER TABLE "TB_03_AC" MODIFY ("CAPACITY" NOT NULL ENABLE);
  ALTER TABLE "TB_03_AC" MODIFY ("STANDARD" NOT NULL ENABLE);
  ALTER TABLE "TB_03_AC" MODIFY ("SELL_YN" NOT NULL ENABLE);
  ALTER TABLE "TB_03_AC" MODIFY ("SCHOOL_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_03_AC" MODIFY ("BUY_YEAR" NOT NULL ENABLE);
  ALTER TABLE "TB_03_AC" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_03_AC" ADD CONSTRAINT "PK_TB_03_AC" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_05_APPLICATION
--------------------------------------------------------

  ALTER TABLE "TB_05_APPLICATION" MODIFY ("END_YN" NOT NULL ENABLE);
  ALTER TABLE "TB_05_APPLICATION" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_APPLICATION" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_APPLICATION" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_05_APPLICATION" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_APPLICATION" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_05_APPLICATION" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_05_APPLICATION" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_APPLICATION" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "TB_05_APPLICATION" MODIFY ("GUBUN" NOT NULL ENABLE);
  ALTER TABLE "TB_05_APPLICATION" MODIFY ("JOB" NOT NULL ENABLE);
  ALTER TABLE "TB_05_APPLICATION" MODIFY ("SEX" NOT NULL ENABLE);
  ALTER TABLE "TB_05_APPLICATION" MODIFY ("LOC_SEQ" NOT NULL ENABLE);
  ALTER TABLE "TB_05_APPLICATION" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_05_APPLICATION" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_05_APPLICATION" MODIFY ("SEQ" NOT NULL ENABLE);
  ALTER TABLE "TB_05_APPLICATION" ADD CONSTRAINT "PK_TB_05_APPLICATION" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_02_AP
--------------------------------------------------------

  ALTER TABLE "TB_02_AP" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_02_AP" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_02_AP" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_02_AP" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_02_AP" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_02_AP" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_02_AP" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_02_AP" ADD CONSTRAINT "PK_TB_02_AP" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_07_FAQ
--------------------------------------------------------

  ALTER TABLE "TB_07_FAQ" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_07_FAQ" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_07_FAQ" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_07_FAQ" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_07_FAQ" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_07_FAQ" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_07_FAQ" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_07_FAQ" ADD CONSTRAINT "PK_TB_07_FAQ" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_06_FB
--------------------------------------------------------

  ALTER TABLE "TB_06_FB" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_FB" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_06_FB" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_FB" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_06_FB" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_06_FB" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_06_FB" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_FB" ADD CONSTRAINT "PK_TB_06_FB" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_06_CS
--------------------------------------------------------

  ALTER TABLE "TB_06_CS" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "TB_06_CS" MODIFY ("UDT_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_CS" MODIFY ("UDT_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_06_CS" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_CS" MODIFY ("REG_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_06_CS" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "TB_06_CS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "TB_06_CS" ADD CONSTRAINT "PK_TB_06_CS" PRIMARY KEY ("SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SURVEY"  ENABLE;
